### ISSUE TITLE
Installation guide and example

### ISSUE THREAD

**Issue by ocgltd** [nedrysoft/qt-ribbon#6]
I realize there are already a couple of similar issues, but I wanted to suggest you include a complete sample in your code.  As well, you need to create a detailed instruction guide (including for plugin).

I've struggled with this project and put the project on hold for a few months.  Thinking about trying again today.  The ribbon screenshot looks great, but I think the lack of guide and example are really hindering your project.

**Comment by fizzyade** [comment]
> I realize there are already a couple of similar issues, but I wanted to suggest you include a complete sample in your code. As well, you need to create a detailed instruction guide (including for plugin).
> 
> I've struggled with this project and put the project on hold for a few months. Thinking about trying again today. The ribbon screenshot looks great, but I think the lack of guide and example are really hindering your project.

I have long term chronic health issues and the past year has seen an even more dramatic deterioration in my day-to-day life and has resulted in a significant reduction in my ability to do even normal daily tasks, let alone work on projects in my free time.

The libraries here are provided as-is, I do not have the energy to devote time to document or provide more examples than what is currently available, these libraries were written by myself to provide specific functionality for some personal projects that I had been working on, and they exist in their own repo's so that I can utilise the code as submodules in other projects, this way I can fix issues and add functionality in a single place and simply update the submodules in the project that uses the code.

These were never intended for third parties, I developed them for my own use and whatever documentation or examples that exist currently should be considered a bonus.

Pingnoo provides the most comprehensive example of using the libraries, the ribbon in particular was designed for use in the dmg creator but was then re-used in Pingnoo, any additional features were then directly created as and when I needed specific functionality in the ribbon in Pingnoo.

I would happily accept pull requests if somebody wanted to provide examples and extend the functionality, but I am not currently in a position to use whatever energy I have on adding more documentation or examples to the this code currently.

**Comment by ocgltd** [comment]
I understand and wish you a speedy recovery (hopefully not COVID related).

I think this is a very cool looking project, hopefully one of the other users will jump in and help.  Lots of potential if we can make it more accessible to all.
